name: Build & Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    env:
      CI: true
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v1

      - name: Setup Node env ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          cache: yarn
          cache-dependency-path: yarn.lock
          node-version: ${{ matrix.node-version }}

      - name: yarn install, build, and test
        run: |
          yarn --frozen-lockfile
          yarn lint
          yarn build
          yarn test:coverage
